<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <WinUISDKReferences>false</WinUISDKReferences>
    <EnableMsixTooling>true</EnableMsixTooling>
    <ApplicationManifest>..\..\..\app.manifest</ApplicationManifest>
    <ApplicationIcon>..\..\..\Assets\AppIcon.ico</ApplicationIcon>
    <AssemblyName>AnotherDSHL.Installer</AssemblyName>
    <Platforms>x64</Platforms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DefineConstants>$(DefineConstants);DISABLE_XAML_GENERATED_MAIN</DefineConstants>
    <PublishReadyToRun>false</PublishReadyToRun>
    <PublishTrimmed>false</PublishTrimmed>
    <Version>0.0.2-beta</Version>
  </PropertyGroup>
  <ItemGroup>
    <Page Remove="InstallerApp.xaml" />
    <ApplicationDefinition Include="InstallerApp.xaml" />
    <Content Include="..\..\..\Assets\AppIcon.ico" Link="Assets\AppIcon.ico" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\..\Assets\AeryoAppIcon.svg" Link="Assets\AeryoAppIcon.svg" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\..\Assets\AeryoLogoMono.svg" Link="Assets\AeryoLogoMono.svg" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\..\Assets\Square44x44Logo.scale-200.png" Link="Assets\Square44x44Logo.scale-200.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\..\Assets\Square44x44Logo.targetsize-48_altform-lightunplated.png" Link="Assets\Square44x44Logo.targetsize-48_altform-lightunplated.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\..\LICENSE" Link="LICENSE" CopyToOutputDirectory="PreserveNewest" />
    <ProjectReference Include="..\Installer.Core\Installer.Core.csproj" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2705" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.5.1" />
  </ItemGroup>
</Project>
