using System.Text.Json;
using AnotherDSHL.Services;

var root = Path.Combine(Path.GetTempPath(), "adl-workspace-tests-" + Guid.NewGuid().ToString("N"));
Directory.CreateDirectory(root);
var a = Path.Combine(root, "ProjectA");
var b = Path.Combine(root, "ProjectB");
var c = Path.Combine(root, "ProjectC");
foreach (var path in new[] { a, b, c }) Directory.CreateDirectory(path);
File.WriteAllText(Path.Combine(a, "keep.txt"), "user project");
File.WriteAllText(Path.Combine(b, "package.json"), "{}");
Directory.CreateDirectory(Path.Combine(c, ".git"));
var deep = Path.Combine(c, "Nested", "DeepProject");
Directory.CreateDirectory(deep);
File.WriteAllText(Path.Combine(deep, "package.json"), "{}");
var checks = 0;
void Check(bool result, string description) { if (!result) throw new Exception(description); checks++; Console.WriteLine("PASS " + description); }
void Reject(Action action, string description) { try { action(); } catch { Check(true, description); return; } throw new Exception(description); }
var file = Path.Combine(root, "state", "workspaces.json");
var store = new WorkspaceCatalogService(file, a, "0.1.5-rc.3", "pack-a");
Check(store.Selected is { Version: "0.1.5-rc.3", PackId: "pack-a" } && store.Selected.Path == a, "migrate legacy path and launch configuration");
Check(store.Selected?.IsolatedHarness == false, "legacy workspaces keep shared mode");
store.SetIsolation(true);
Check(new WorkspaceCatalogService(file, c).Selected?.IsolatedHarness == true, "isolation persists across restart");
store.Add(a + Path.DirectorySeparatorChar);
Check(store.Current.Items.Count == 1, "normalized paths do not duplicate");
store.Add(b);
store.Select(b);
Check(!store.Selected!.IsolatedHarness, "new workspace isolation choice is independent");
store.SaveConfiguration("0.2.0-rc.2", "pack-b");
store.SetAutomation(false, true);
var loaded = new WorkspaceCatalogService(file, c);
Check(loaded.Selected?.Path == b && loaded.Selected.Version == "0.2.0-rc.2" && loaded.Selected.PackId == "pack-b", "restart restores selected path and launch configuration");
Check(!loaded.Current.AutoDiscover && loaded.Current.RestoreConfiguration, "automation choices persist");
loaded.Select(a);
Check(loaded.Selected?.PackId == "pack-a" && loaded.Selected.Version == "0.1.5-rc.3", "switching restores independent configuration");
Check(loaded.Selected?.IsolatedHarness == true, "switching restores per-workspace isolation");
loaded.SetIsolation(false);
Check(loaded.Selected?.IsolatedHarness == false && loaded.Selected.PackId == "pack-a", "turning isolation off preserves version and pack choice");
loaded.Remove(a);
Check(loaded.Selected?.Path == b && File.ReadAllText(Path.Combine(a, "keep.txt")) == "user project", "remove selects remaining entry and preserves project files");
loaded.Remove(b);
Check(loaded.Selected is null && loaded.Current.Items.Count == 0, "last removal leaves an empty catalog");
Check(new WorkspaceCatalogService(file, a).Selected is null, "empty catalog stays empty after restart");
Reject(() => loaded.Add(Path.Combine(root, "Missing")), "reject non-existent paths");
Reject(() => loaded.Add("relative-project"), "reject relative paths");
var discoveries = WorkspaceCatalogService.Discover([root], [b]);
Check(discoveries.Count == 1 && discoveries[0].Path == c, "discover projects and exclude already saved directories");
Check(discoveries.All(item => item.Path != deep), "discovery does not recursively traverse projects");
var goneFile = Path.Combine(root, "gone.json");
File.WriteAllText(goneFile, JsonSerializer.Serialize(new WorkspaceCatalog([new(Path.Combine(root, "Gone"))], Path.Combine(root, "Gone"))));
var gone = new WorkspaceCatalogService(goneFile, a);
Check(gone.Selected?.Path.EndsWith("Gone") == true && gone.Selected.Availability.Contains("不存在"), "retain missing paths for user repair");
var corruptFile = Path.Combine(root, "corrupt.json");
File.WriteAllText(corruptFile, "invalid user catalog");
var corrupt = new WorkspaceCatalogService(corruptFile, a);
Reject(() => corrupt.Add(b), "unreadable catalog is protected from overwrite");
Check(File.ReadAllText(corruptFile) == "invalid user catalog", "corrupt source file remains intact");
Console.WriteLine($"{checks} workspace checks passed. QA root: {root}");
